// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjt7gN33hVwzulD8iya77nt--zVVquchk',
    appId: '1:546717421353:web:cd5b01c0ac5d52923ff138',
    messagingSenderId: '546717421353',
    projectId: 'suganya-social-login',
    authDomain: 'suganya-social-login.firebaseapp.com',
    storageBucket: 'suganya-social-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxlQQl8jVF0J5qiR8LYtjpcsspKKS-zqc',
    appId: '1:546717421353:android:cc68a5680e3b102e3ff138',
    messagingSenderId: '546717421353',
    projectId: 'suganya-social-login',
    storageBucket: 'suganya-social-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSMoRGOjEEKvQmjq1FyIY7aiNUz_cUAQ',
    appId: '1:546717421353:ios:e00fb43b7db700fe3ff138',
    messagingSenderId: '546717421353',
    projectId: 'suganya-social-login',
    storageBucket: 'suganya-social-login.appspot.com',
    iosClientId: '546717421353-7rds5leef59a1qk03fuvvpbb7kks9egu.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLogin',
  );
}
